version: '3'
services:
  app:
    container_name: go-app
    build: .
    volumes:
      - type: bind
        source: .
        target: /root/go-app
    working_dir: /root/go-app
    entrypoint: bash
    stdin_open: true
    tty: true
    ports:
      - 8880:8880
